"""users and vessel

Revision ID: 986db58b4143
Revises: 
Create Date: 2026-10-01 00:14:06.724951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986db58b4143'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='operator', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vessel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('imo', sa.String(length=16), nullable=True),
    sa.Column('mmsi', sa.String(length=16), nullable=True),
    sa.Column('call_sign', sa.String(length=16), nullable=True),
    sa.Column('flag', sa.String(length=16), nullable=True),
    sa.Column('vessel_type', sa.String(length=32), nullable=True),
    sa.Column('operator', sa.String(length=200), nullable=True),
    sa.Column('max_ice_thickness_m', sa.Float(), nullable=True),
    sa.Column('max_sic', sa.Float(), nullable=True),
    sa.Column('iacs_polar_class', sa.String(length=8), nullable=True),
    sa.Column('polar_code_category', sa.String(length=4), nullable=True),
    sa.Column('draft_loaded_m', sa.Float(), nullable=True),
    sa.Column('draft_ballast_m', sa.Float(), nullable=True),
    sa.Column('max_wind_speed_kt', sa.Float(), nullable=True),
    sa.Column('max_wave_height_m', sa.Float(), nullable=True),
    sa.Column('economical_speed_kt', sa.Float(), nullable=True),
    sa.Column('max_speed_kt', sa.Float(), nullable=True),
    sa.Column('speed_in_ice_kt', sa.Float(), nullable=True),
    sa.Column('fuel_capacity_t', sa.Float(), nullable=True),
    sa.Column('fuel_burn_economical_tpd', sa.Float(), nullable=True),
    sa.Column('endurance_days', sa.Float(), nullable=True),
    sa.Column('crane_outreach_m', sa.Float(), nullable=True),
    sa.Column('has_helideck', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_hangar', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_rov', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('shaft_power_kw', sa.Float(), nullable=True),
    sa.Column('bow_shape', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo')
    )
    op.create_index(op.f('ix_vessel_user_id'), 'vessel', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessel_user_id'), table_name='vessel')
    op.drop_table('vessel')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
